line-length = 100
target-version = "py310"
fix = true

[lint]
select = ["E", "F", "I", "UP"]  # pycodestyle, pyflakes, isort, pyupgrade
ignore = ["E501"]               # example: ignore line length if needed

[format]
quote-style = "double"
indent-style = "space"
