services:
  notebook:
    container_name: notebook_medvisor
    image: notebook-medvisor
    build:
      context: ai_services
      target: notebook
    ports:
      - 8899:8888
    env_file:
      - path: .env
        required : false
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/credentials.json
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=medvisor-experiment
      - MLFLOW_RUN=medvisor-run
    volumes:
      - ./ai_services/:/code
      - ./.credentials/local-credentials.json:/tmp/keys/credentials.json:ro
      - mlflow-data:/mlflow
    tty: true

  vscode-server:
    container_name: vscode-server-medvisor
    image: vscode-server-medvisor
    build:
      context: ai_services
      target: vscode
    env_file:
      - path: .env
        required : false
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/credentials.json
    volumes:
      - ./ai_services/:/code
      - ./.credentials/local-credentials.json:/tmp/keys/credentials.json:ro
    tty: true

  ai-services:
    container_name: ai-services-medvisor
    image: ai-services-medvisor
    build:
      context: ai_services
      target: dev
    ports:
      - 8001:8000
    env_file:
      - path: .env
        required : false
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/credentials.json
    volumes:
      - ./ai_services/:/code
      - ./.credentials/local-credentials.json:/tmp/keys/credentials.json:ro
    tty: true

  mlflow:
    container_name: mlflow-medvisor
    image: mlflow-medvisor
    build:
      context: ai_services
      target: mlflow
    ports:
      - 5001:5000
    volumes:
      - mlflow-data:/mlflow
    restart: unless-stopped
    tty: true

volumes:
  mlflow-data:
